title: "Youngjin Cho"
author: "Youngjin Cho"
theme: "minima"
url: "https://yourusername.github.io"
baseurl: "/"
markdown: kramdown
header_pages:
  - index.md
  - cv.md
  - software.md

# SEO metadata
description: "Youngjin Cho is a tenure-track assistant professor in the Department of Mathematical Sciences at the University of Nevada, Las Vegas. Research interests lie in statistical methodology, include Smoothing Splines, Functional Data Analysis, Survival Analysis, and High-Dimensional Statistics."
keywords: "Youngjin Cho, Statistics, University of Nevada, Las Vegas, Smoothing Splines, Functional Data Analysis, Survival Analysis, High-Dimensional Statistics"
